[phases.setup]
nixPkgs = ["python313"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python3 run.py"

[phases.build]
cmds = ["echo 'Build v4.1.1 - Mini App + Android fix'"]
